apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3-tier-app
  namespace: argocd
  annotations:
    image-updater.argoproj.io/frontend.image-name: 120496071282.dkr.ecr.ap-south-1.amazonaws.com/rohit_ecr
    image-updater.argoproj.io/backend.update-strategy: latest
    image-updater.argoproj.io/frontend.update-strategy: latest
    image-updater.argoproj.io/write-back-target: kustomize:./declarative_node-pro
    image-updater.argoproj.io/git-credentials: argocd/git-creds
spec:
  project: default
  source:
    repoURL: https://github.com/rohitG7496/ArgoCD-GitOps.git
    targetRevision: main
    path: declarative_node-pro
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
