apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      backend=120496071282.dkr.ecr.ap-south-1.amazonaws.com/rohit_ecr:backend,
      frontend=120496071282.dkr.ecr.ap-south-1.amazonaws.com/rohit_ecr:frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.set-application-resource: Deployment/backend:spec.template.spec.containers[0].image
    argocd-image-updater.argoproj.io/frontend.set-application-resource: Deployment/frontend:spec.template.spec.containers[0].image
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/rohitG7496/ArgoCD-GitOps.git
    targetRevision: main
    path: declarative_node-pro
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
