apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: 3-tier-app
  namespace: argocd
spec: 
  project: default
  source: 
    repoURL: https://github.com/rohitG7496/ArgoCD-GitOps.git
    targetRevision: main
    path: declarative_node-pro
  destination: 
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
  syncOptions: 
    - CreateNameSpace=true    
    