---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tradein-aws-store
    kind: ClusterSecretStore
  target:
    name: argocd-oauth-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd/in/github-sso
